### ISSUE TITLE
Responses with bodies do not contain the object that was expected

### ISSUE THREAD

**Issue by mmmasent** [CenterEdge/Yardarm#10] opened 2020-11-29 22:35 UTC
An example response from an endpoint that has an expected return value:
![image](https://user-images.githubusercontent.com/29384916/100555367-01ea0180-3269-11eb-8b01-041d5c0ba133.png)

The response object is a complex http object, with a few helper methods. The response should probably be more simplistic,
i.e. a Value object that represents the body of the response as a value of <T> so that there is no need to convert it by the consumer. Maybe the object itself could be the object of <T> and the helpers are simply additional helper GET properties on it. Either way, the current object requires a lot of consumer overhead to retrieve the intended object that should not be necessary.

**Comment by brantburnett** [comment] 2021-02-28 20:55
This is actually by design, and intended to address the highly flexible nature of the OpenAPI schemas and REST. Each different HTTP response may have a completely different schema. There was a lot of debate over the best way to handle it, and eventually we settled on C# 8 type switching as a pretty elegant consumer pattern (given the constraints).

```csharp
switch (getUserAccountResult)
{
    case GetUserAccountOkResponse okResponse:
        // Handle OK case
        break;
    default:
        // Handle other cases
        break;        
}
```

However, for more simplistic scenarios, extension methods are provided:

```csharp
var okBody = await getUserAccountResult.AsOk().GetBodyAsync();
```

These extensions will throw an exception if the status code doesn't match.

I believe this should meet your needs, so I'm closing this issue, but feel free to reopen it if you still have concerns.

**Closed by brantburnett** 2021-02-28 20:55 UTC
