### ISSUE TITLE
Client Request Generation

### ISSUE THREAD

**Issue by mmmasent** [CenterEdge/Yardarm#7] opened 2020-11-23 04:50 UTC
A build of the tool from the local source code results in a client that has more complex request setups than the alpha 003 version that is available (at the time of this writing). Additionally, there are now 2 separate request objects, one from alpha 003 that is missing the body field and a new one, from the local source code, that contains a body. 

```
v003 Alpha, has single request:
new ApiRequestName() {
   Authenticators = null // default
   Body = new ApiRequest() {
                    SomePropA = "Ya ya",
                    SomePropB= "Who are you!?"
   }
}

Source:
new ApiRequestName() {
   Authenticators = null // default
   // Body Missing here
}
new ApiRequestNameHttpContentRequest()
            {
                Authenticators = null // default,
                Body = new StringContent(JsonConvert.SerializeObject(new ApiRequestName()
                {
                    SomePropA = "Ya ya",
                    SomePropB= "Who are you!?"
                }), Encoding.UTF8, "application/json")
            }
```

It seems as though the intent was to replace the original v003 alpha request object with the new http request, which might allow for more http content body types (streams/byte/string/etc.)

The current http request object does work, but it is cumbersome and has a slightly complex setup. The api client expects the http request object type, rather than the main request type that the api controller requires.

Suggestions:
- Remove the old request object entirely, since it is redundant and seemingly unusable.
- Update the new http request object to be more streamlined. Ideally, the only thing that would need to be sent is the api request itself, rather than a complex http request object that the user must define all properties for, Maybe the addition of a request builder object, if needed.

**Comment by brantburnett** [comment] 2021-03-06 22:37
@mmmasent You are correct that it was designed to allow for multiple content types. It allows the selection of a particular content type easily if a REST endpoint supports multiple content types. The original request class is there to be an abstract type base for the different content types.

At first, I considered having just one class, as you suggest, in cases where there is only one content type. However, I discarded that idea. It creates a backward compatibility issue if the API ever adds a second content type to the specification. One of the goals of the project is that if the API spec is updated with non-breaking additions then the generated C# SDK is also still compatible. A sudden change in parameter types and the addition of multiple variants would break that rule.

I agree, the current approach is a bit cumbersome. Therefore, I'm thinking that adding overloads or extension methods that are strongly typed to specific content types may be a cleaner way to expose the possible types to the consumer. I'll look into it.

**Comment by brantburnett** [comment] 2021-05-16 18:36
@mmmasent After digging into this more deeply, I've determined that it's by design. Specifically, it's to account for optional request bodies. If the body is optional, you can use the base request type and leave the body null. If the body is not optional, the base request type is marked as abstract so that you must choose a specific body type such as Json.

I believe you can reduce your confusion by adding the `"required": true` attribute to your `requestBody` in the source OpenAPI schema.

**Closed by brantburnett** 2021-05-16 18:36 UTC
